### ISSUE TITLE
Where can I get this project?

### ISSUE THREAD

**Issue by devonjones** [CalamarRojo/FrostGraveTreasures#1]
The dropbox urls are dead.

Any chance you would consider putting it up on the play store?  If you don't want to do the work, I have an open source gaming app and play account, and I could put it up for you.

**Comment by CalamarRojo** [comment]
Hi! I asked to the game designer for permission to put it on Google play and he didn't want so I can't :/. You can download the apk from this link https://boardgamegeek.com/filepage/141543/frostgrave-random-treasure-generator-android If you want to improve the app, feel free :) I'm pro open code
